on:
  push:
    branches: [ master ]
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Auto Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@3.1.2
      with:
        ftp-server: ftp.keifproject.com
        ftp-username: u1584221
        ftp-password: ${{ secrets.DEPLOY_KEY }}
