on:
  push:
    branches: [ master ]
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Auto Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2

    - name: 📂 Sync files
      uses: Burnett01/rsync-deployments@5.2.1
      with:
        switches: -avzr --delete --exclude=".git" --exclude=".github"
        path: /var/www/yusuf.keifproject.com/
        remote_path: public_html/yusuf.keifproject.com
        remote_host: yusuf.keifproject.com
        remote_user: u1584221
        remote_key: ${{ secrets.DEPLOY_KEY }}
